spring.application.name=devops-hello
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/devops}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:devops}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:devops}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
